### ISSUE TITLE
Error when `pip install`

### ISSUE THREAD

**Issue by mindflayer** [mozilla/django-post-request-task#19]
`ERROR: django-post-request-task 0.4.0 has requirement Django<=2.2,>=1.11, but you'll have django 2.2.3 which is incompatible.`

In `setup.py` we have:
```
install_requires = [
    'Django>=1.11,<=2.2',
    'celery>=3.0,<5.0',
]
```

Can you please change it to:
```
    'Django>=1.11,<2.3',
    'celery>=3.0,<5.0',
```
and release a new version?

**Comment by diox** [comment]
Fixed in https://github.com/mozilla/django-post-request-task/commit/f2e8596d70a031dca5ef3bfab91ef1d66fc70577 we'll prepare a release.

**Comment by mindflayer** [comment]
@diox do you have a plan to release it this week?

**Comment by diox** [comment]
I thought I pushed a release last Friday... let me check why that didn't work.

**Comment by diox** [comment]
0.4.1 is now up on PyPI.

**Comment by mindflayer** [comment]
Hi again, and sorry for bothering you.
It seems that the package is not available for Python 3.
```
Collecting django-post-request-task==0.4.1 (from -r requirements.txt (line 40))
  Could not find a version that satisfies the requirement django-post-request-task==0.4.1 (from -r requirements.txt (line 40)) (from versions: 0.1.1, 0.2.0, 0.4.0)
No matching distribution found for django-post-request-task==0.4.1 (from -r requirements.txt (line 40))
```

**Comment by diox** [comment]
Sigh. I hate packaging.

**Comment by mindflayer** [comment]
Need help? I'd love to work for Mozilla. :P

**Comment by diox** [comment]
This should be fixed, I accidentally built it using python 2 without the universal flag earlier :(

**Comment by mindflayer** [comment]
Bingo!
```Successfully django-post-request-task-0.4.1```
