### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by bfmcneill** [mozilla/django-post-request-task#20]
question: 

This package looks awesome, the activity looks low since django3.0 came out, Would you say it is stable with django 3.0?

**Comment by diox** [comment]
Hi,

We aren't running Django 3.0 yet but I suspect it works fine with it. You are welcome to try it, report back, and maybe submit a PR to add Django 3.0 to the [test matrix](https://github.com/mozilla/django-post-request-task/blob/master/tox.ini)!
