### ISSUE TITLE
Celery 5 support

### ISSUE THREAD

**Issue by ron8mcr** [mozilla/django-post-request-task#24]
Thanks for elegant solution of celery/django/transactions integration.

Celery released new major version [5.0.0 on September, 24 2020](https://docs.celeryproject.org/en/stable/whatsnew-5.0.html). It would be nice to see it's support in this project, but celery version limited in [setup.py](https://github.com/mozilla/django-post-request-task/blob/ac2cf8eb1adf051579045d8cd51cc64606e0b6b0/setup.py#L26)

**Comment by diox** [comment]
Hi,

Celery 4.x is supported until August 2021, so that's what we're still using and haven't had the time to test Celery 5. If you want, feel free to adjust `setup.py` and `tox.ini` to run the tests locally with that version and file a pull request adding support.
